version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Ivan0680790898@"
      MYSQL_DATABASE: "admin_panel_db"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./Backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Ivan0680790898@
      - MYSQL_DATABASE=admin_panel_db
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=admin_panel_db
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./Backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./Frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5002/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  db_data:
